# Generated by Django 3.2.7 on 2021-10-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='business_name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imágen/Logo'),
        ),
    ]
