# Generated by Django 3.2.7 on 2021-11-20 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211013_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='control_stock',
            field=models.BooleanField(default=False, verbose_name='Controla Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bread',
            field=models.BooleanField(default=False, verbose_name='Es Pan'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('U', 'Unidades')], default='U', max_length=4, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
